package practical_exception;
public class ExceptionPractice {
public static void main(String[] args) {

//	try {
//		int den=Integer.parseInt(args[5]);
//		try {
//			System.out.println(3/den);;
//		} catch (ArithmeticException e) {
//			e.printStackTrace();
//			
//		}
//	} catch (ArrayIndexOutOfBoundsException ab) {
//		
//		// TODO: handle exception
//	}
	System.out.println(3/9);
	System.out.println("please print me ");
}
}
